# Site settings
title: 쇼마
description: '쇼핑 마스터, 쇼핑, 추천, 제품, 가성비'
url: 'https://sixfigure999999.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'sixfigure999999'
  email: sixfigure999999@gmail.com
  # twitter_username: sixfigure999999.github.io
  # facebook_username: sixfigure999999.github.io
  # github_username:  sixfigure999999.github.io
  # linkedin_username:  sixfigure999999.github.io

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /posts/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'node_modules', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/', 'any_additional_item ']
