# Site settings
title: 쇼마
description: '쇼핑 마스터, 추천, 상품, 제품'
url: 'https://sixfigure999999.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'shoping'
  email: sixfigure999999.github.io
  twitter_username: sixfigure999999.github.io
  facebook_username: sixfigure999999.github.io
  github_username:  sixfigure999999.github.io
  linkedin_username:  sixfigure999999.github.io

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
